name: network_it_lead_planner_and_followup
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.0       # State management
  dio: ^5.4.0                    # Network calls
  google_sign_in: ^7.1.1         # Google OAuth
  intl: ^0.19.0                  # Date formatting
  url_launcher: ^6.3.0           # Open links (Email/LinkedIn)
  flutter_spinkit: ^5.2.0        # Loading indicators
  shared_preferences: ^2.2.3     # Local storage for tokens
  go_router: ^14.1.0             # Navigation
  json_annotation: ^4.9.0        # Model serialization
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  sign_in_button: ^4.0.1
  google_fonts: ^6.3.0
  flutter_styled_toast: ^2.2.1
  google_sign_in_web: ^1.0.0
  flutter_spinbox: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Images/background.png
    - assets/Images/logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg